services:
  pgdb:
    image: postgres:15
    container_name: signalvc-pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.local/pgdata:/var/lib/postgresql/data
      - ./.data/pgdb/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: signalvc-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      APP_MODULE: ${APP_MODULE:-api.server:app}
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      APP_LOG_LEVEL: ${APP_LOG_LEVEL:-debug}
      POSTGRES__USER: ${POSTGRES__USER}
      POSTGRES__PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES__DB: ${POSTGRES__DB}
      POSTGRES__HOST: ${POSTGRES__HOST}
      POSTGRES__PORT: 5432
    volumes:
      - ./apps/api/src:/app/src
