services:
  pgdb:
    image: postgres:15
    container_name: signalvc-pgdb
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_DB: ${POSTGRES__DB}
    ports:
      - "5432:5432"
    volumes:
      - ./.local/pgdata:/var/lib/postgresql/data
      - ./.data/pgdb/init:/docker-entrypoint-initdb.d
